apiVersion: v1
kind: Service
metadata:
  name: ds-images-client-service
spec:
  selector:
    app: ds-images-client
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort : 31111
