apiVersion: apps/v1
kind: Deployment
metadata:
  name: ds-images-client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ds-images-client
  template:
    metadata:
      labels:
        app: ds-images-client
    spec:
      containers:
      - name: ds-images-client
        image: xywings/ds-images-1:clientfrontend
        ports:
        - containerPort: 3000
