apiVersion: v1
kind: Service
metadata:
  name: ds-images-course-service
spec:
  selector:
    app: ds-images-course
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
      nodePort: 31110