apiVersion: apps/v1
kind: Deployment
metadata:
  name: ds-images-course-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ds-images-course
  template:
    metadata:
      labels:
        app: ds-images-course
    spec:
      containers:
      - name: ds-images-course
        image: xywings/ds-images-1:coursebackend
        ports:
        - containerPort: 8090

---

apiVersion: v1
kind: Service
metadata:
  name: ds-images-course-service
spec:
  selector:
    app: ds-images-course
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
      nodePort: 30400
