apiVersion: v1
kind: Service
metadata:
  name: ds-images-enrolment-service
spec:
  selector:
    app: ds-images-enrolment
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8071
      targetPort: 8071
      nodePort: 31112