apiVersion: apps/v1
kind: Deployment
metadata:
  name: ds-images-enrolment-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ds-images-enrolment
  template:
    metadata:
      labels:
        app: ds-images-enrolment
    spec:
      containers:
      - name: ds-images-enrolment
        image: xywings/ds-images-1:enrolmentbackend
        ports:
        - containerPort: 8071
