apiVersion: apps/v1
kind: Deployment
metadata:
  name: ds-images-enrolment-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ds-images-enrolment
  template:
    metadata:
      labels:
        app: ds-images-enrolment
    spec:
      containers:
      - name: ds-images-enrolment
        image: xywings/ds-images-1:enrollment-backend
        ports:
        - containerPort: 8071
---

apiVersion: v1
kind: Service
metadata:
  name: ds-images-enrolment-service
spec:
  selector:
    app: ds-images-enrolment
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8071
      targetPort: 8071
      nodePort: 30300