apiVersion: v1
kind: Service
metadata:
  name: ds-images-user-service
spec:
  selector:
    app: ds-images-user
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31114