apiVersion: apps/v1
kind: Deployment
metadata:
  name: ds-images-user-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ds-images-user
  template:
    metadata:
      labels:
        app: ds-images-user
    spec:
      containers:
      - name: ds-images-user
        image: xywings/ds-images-1:userbackend
        ports:
        - containerPort: 8080
---

apiVersion: v1
kind: Service
metadata:
  name: ds-images-user-service
spec:
  selector:
    app: ds-images-user
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30100