apiVersion: v1
kind: Service
metadata:
  name: ds-images-payment-service
spec:
  selector:
    app: ds-images-payment
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8070
      targetPort: 8070
      nodePort: 31113