apiVersion: apps/v1
kind: Deployment
metadata:
  name: ds-images-user-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ds-images-user
  template:
    metadata:
      labels:
        app: ds-images-user
    spec:
      containers:
      - name: ds-images-user
        image: xywings/ds-images-1:userbackend
        ports:
        - containerPort: 8080
