apiVersion: apps/v1
kind: Deployment
metadata:
  name: ds-images-payment-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ds-images-payment
  template:
    metadata:
      labels:
        app: ds-images-payment
    spec:
      containers:
      - name: ds-images-payment
        image: xywings/ds-images-1:paymentbackend
        ports:
        - containerPort: 8070
